version: '3.8'

services:
  db-teste:
    image: postgres:latest
    environment:
      POSTGRES_DB: vollmed_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: vollmed_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"